### ISSUE TITLE
Optimise Landing page for small screens (mobile phones)

### ISSUE THREAD

**Issue by ayan-b** [sarnava1/YelpCampBlog#1]

**Comment by sarnava1** [comment]
Hey ayan-b can you elaborate on the issue you have raised so that our contributors can understand the issue better?

**Comment by ayan-b** [comment]
@sarnava1 One needs to zoom in in order to tap on the `View all Playgrounds`. I guess the button may be made bigger on small screens like mobile phones. :iphone:

**Comment by sarnava1** [comment]
Okay I will be looking into the issue you created and try to fix it!!!
